#
# NOTE: this is the circleci config which is used to publish @adobe/create-helix-service
# to NPM. The circleci config for the actual service to be created is in templates/.circleci
# and will be patched.
#
version: 2.1
executors:
  node18:
    docker:
      - image: cimg/node:18.19

orbs:
  codecov: codecov/codecov@3.3.0
  helix-post-deploy: adobe/helix-post-deploy@3.0.1

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm ci
      - run:
          name: prepare test git user
          command: git config --global user.email "freyjabot@adobe.com" && git config --global user.name "Freyja Bot"

jobs:
  build:
    executor: node18
    steps:
      - setup
      - run: mkdir junit
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Getting Code Coverage
          command: npm run test
      - codecov/upload
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit

  semantic-release:
    executor: node18
    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json
      - helix-post-deploy/config-env
      - run:
          name: Semantic Release
          command: npm run semantic-release
      - store_test_results:
          path: junit

  branch-deploy:
    executor: node18
    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json
      - run:
          name: Branch Deployment
          command: npm run deploy-ci
      - run:
          name: Post-Deployment Integration Test
          command: npm run test-postdeploy
      - store_test_results:
          path: junit

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Freyja
      - branch-deploy:
          context: Freyja
          requires:
            - build
          filters:
            branches:
              ignore: main
      - semantic-release:
          context: Freyja
          requires:
            - build
          filters:
            branches:
              only: main
