name: Semantic Release
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v4 # v4
        with:
          persist-credentials: false
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
        env:
          NPM_AUTH: ${{ secrets.NPM_AUTH }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
      - run: npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH: ${{ secrets.NPM_AUTH }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
